service: slack-notion-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  deploymentMethod: direct
  environment: 
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}
    NOTION_TOKEN: ${env:NOTION_TOKEN}
    TEAM_JOON_CHANNEL: ${env:TEAM_JOON_CHANNEL}
    DEBUG_CHANNEL: ${env:DEBUG_CHANNEL}


functions:
  slackBotHandler:
    handler: dist/utils/function/lambdaHandler/handler.handler
    timeout: 15
    events:
     - httpApi:
        method: POST
        path: /slack/events
     - httpApi:
        method: POST
        path: /slack/command
     - httpApi:
        method: POST
        path: /slack/uploadNotion
  SendBlogInfoToSlackSchedule:
    handler: dist/scheduler/sendBlogInfoToSlackChannel.handler
    timeout: 20
    events:
      - schedule:
          rate: cron(0 0 ? * 2 *)

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: slack.team-joon.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false 
