service: slack-notion-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  deploymentMethod: direct
  environment: 
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}
    NOTION_TOKEN: ${env:NOTION_TOKEN}

functions:
  slackBotHandler:
    handler: dist/server/utils/function/lambdaHandler/handler.handler
    events:
     - httpApi:
        method: POST
        path: /slack/events

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true
