name: Deploy slackBot to Aws Lambda

on:
  push:
    branches:
      - main

jobs:
    serverless-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to main branch
              uses: actions/checkout@v2

            - name: Set up Node.js 18 Version
              uses: actions/setup-node@v1
              with:
                node-version: '18'

            - name: Install dependency
              run: npm install

            - name: Build Typescript code
              run: npm run build

            - name: Login Aws and Deploy to Aws Lambda
              env: 
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}
                SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
                NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
                NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
                TEAM_JOON_CHANNEL: ${{secrets.TEAM_JOON_CHANNEL}}
                DEBUG_CHANNEL: ${{secrets.DEBUG_CHANNEL}}
              run: npm run deploy:production
            